#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
# config/routes.yaml
mailer_route:
    path: /mailer
    controller: App\Controller\MailerController::index
